"use client"

import { useEffect, useRef, useState } from "react"
import Image from "next/image"
import { X, ChevronLeft, ChevronRight } from "lucide-react"

interface GalleryImage {
  id: number
  src: string
}

export function PortfolioGallery() {
  const [images, setImages] = useState<GalleryImage[]>([])
  const [isVisible, setIsVisible] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null)
  const sectionRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    // CHANGED: Fetch the static JSON file generated by the script
    fetch("/portfolio.json")
      .then((res) => {
        if (!res.ok) throw new Error("Failed to load portfolio data")
        return res.json()
      })
      .then((data) => setImages(data))
      .catch((err) => console.error("Error loading images:", err))
  }, [])

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true)
      },
      { threshold: 0.1 }
    )

    if (sectionRef.current) observer.observe(sectionRef.current)

    return () => observer.disconnect()
  }, [])

  const openModal = (index: number) => {
    setSelectedIndex(index)
  }

  const closeModal = () => {
    setSelectedIndex(null)
  }

  const showPrev = (e: React.MouseEvent) => {
    e.stopPropagation() // Prevent modal from closing when clicking buttons
    if (selectedIndex !== null && selectedIndex > 0) {
      setSelectedIndex(selectedIndex - 1)
    }
  }

  const showNext = (e: React.MouseEvent) => {
    e.stopPropagation() // Prevent modal from closing when clicking buttons
    if (selectedIndex !== null && selectedIndex < images.length - 1) {
      setSelectedIndex(selectedIndex + 1)
    }
  }

  return (
    <section ref={sectionRef} className="bg-pista py-16 md:py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Masonry Layout */}
        <div className="columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6">
          {images.map((img, i) => (
            <div
              key={img.id}
              onClick={() => openModal(i)}
              className={`group relative cursor-pointer overflow-hidden rounded-xl break-inside-avoid
                transition-all duration-700
                ${isVisible ? "opacity-100 animate-fade-in" : "opacity-0"}`}
              style={{ animationDelay: `${(i % 10) * 80}ms` }}
            >
              <Image
                src={img.src}
                alt={`Project ${img.id}`}
                width={600}
                height={800}
                className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-110"
              />

              {/* Overlay */}
              <div className="absolute inset-0 bg-forest/0 group-hover:bg-forest/40 transition-all duration-300" />

              {/* Text */}
              <div className="absolute bottom-4 left-4 text-pista-light opacity-0 group-hover:opacity-100 transition-all duration-300">
                <p className="font-semibold text-lg">Project #{img.id}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Fullscreen Modal */}
      {selectedIndex !== null && images[selectedIndex] && (
        <div
          className="fixed inset-0 z-50 bg-forest/90 flex items-center justify-center p-4 animate-fade-in"
          onClick={closeModal}
        >
          <div className="relative w-full max-w-4xl" onClick={(e) => e.stopPropagation()}>
            <button
              className="absolute top-4 right-4 w-10 h-10 flex items-center justify-center rounded-full bg-forest/80 hover:bg-forest text-pista-light z-10"
              onClick={closeModal}
            >
              <X className="w-5 h-5" />
            </button>

            <Image
              src={images[selectedIndex].src}
              alt="Fullscreen"
              width={1600}
              height={1200}
              className="rounded-xl object-contain mx-auto max-h-[85vh] w-auto"
            />

            {/* Prev */}
            <button
              onClick={showPrev}
              disabled={selectedIndex === 0}
              className="absolute left-4 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-forest/70 hover:bg-forest flex items-center justify-center disabled:opacity-40 transition-colors"
            >
              <ChevronLeft className="w-6 h-6 text-pista-light" />
            </button>

            {/* Next */}
            <button
              onClick={showNext}
              disabled={selectedIndex === images.length - 1}
              className="absolute right-4 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-forest/70 hover:bg-forest flex items-center justify-center disabled:opacity-40 transition-colors"
            >
              <ChevronRight className="w-6 h-6 text-pista-light" />
            </button>
          </div>
        </div>
      )}
    </section>
  )
}